# Generated by Django 3.0.5 on 2020-04-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_gif', models.CharField(max_length=200)),
                ('vote_type', models.CharField(max_length=200)),
            ],
        ),
    ]
